[project]
name = "tidal"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8>=7.3.0",
    "icalendar>=6.3.2",
    "ipython>=9.9.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
